application:
  currenciesListUrl:  https://openexchangerates.org/api/currencies.json

spring:
  thymeleaf:
   cache: false
   prefix: classpath:/templates
  messages:
    encoding: UTF-8
    fallback-to-system-locale: true
    basename: i18n/message
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./DB

server: